[2024-12-20T10:39:39.430+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-20T10:39:39.452+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sql_operator_dag.SQL_provider_task scheduled__2024-01-21T11:00:00+00:00 [queued]>
[2024-12-20T10:39:39.464+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sql_operator_dag.SQL_provider_task scheduled__2024-01-21T11:00:00+00:00 [queued]>
[2024-12-20T10:39:39.465+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-20T10:39:39.532+0000] {taskinstance.py:2889} INFO - Executing <Task(SQLExecuteQueryOperator): SQL_provider_task> on 2024-01-21 11:00:00+00:00
[2024-12-20T10:39:39.549+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=15774) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-20T10:39:39.553+0000] {standard_task_runner.py:72} INFO - Started process 15779 to run task
[2024-12-20T10:39:39.556+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sql_operator_dag', 'SQL_provider_task', 'scheduled__2024-01-21T11:00:00+00:00', '--job-id', '5440', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgresql.py', '--cfg-path', '/tmp/tmp62tmcc2x']
[2024-12-20T10:39:39.560+0000] {standard_task_runner.py:105} INFO - Job 5440: Subtask SQL_provider_task
[2024-12-20T10:39:39.694+0000] {task_command.py:467} INFO - Running <TaskInstance: sql_operator_dag.SQL_provider_task scheduled__2024-01-21T11:00:00+00:00 [running]> on host a998b5b3d359
[2024-12-20T10:39:39.966+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mateo' AIRFLOW_CTX_DAG_ID='sql_operator_dag' AIRFLOW_CTX_TASK_ID='SQL_provider_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-21T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-21T11:00:00+00:00'
[2024-12-20T10:39:39.970+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-20T10:39:40.002+0000] {sql.py:278} INFO - Executing: 
        create table if not exists dag_runs_v2(
            dt date,
            dag_id varchar,
            primary key (dt,dag_id) 
        )
        
[2024-12-20T10:39:40.033+0000] {base.py:84} INFO - Retrieving connection 'sql_operator_practice'
[2024-12-20T10:39:40.053+0000] {base.py:84} INFO - Retrieving connection 'sql_operator_practice'
[2024-12-20T10:39:40.083+0000] {sql.py:553} INFO - Running statement: 
        create table if not exists dag_runs_v2(
            dt date,
            dag_id varchar,
            primary key (dt,dag_id) 
        )
        , parameters: None
[2024-12-20T10:39:40.115+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-20T10:39:40.120+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=sql_operator_dag, task_id=SQL_provider_task, run_id=scheduled__2024-01-21T11:00:00+00:00, execution_date=20240121T110000, start_date=20241220T103939, end_date=20241220T103940
[2024-12-20T10:39:40.315+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-20T10:39:40.344+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-20T10:39:40.354+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
