[2024-12-19T08:51:32.401+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T08:51:32.442+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.second_task scheduled__2021-09-30T00:00:00+00:00 [queued]>
[2024-12-19T08:51:32.472+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.second_task scheduled__2021-09-30T00:00:00+00:00 [queued]>
[2024-12-19T08:51:32.474+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-19T08:51:32.587+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): second_task> on 2021-09-30 00:00:00+00:00
[2024-12-19T08:51:32.607+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2534) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-19T08:51:32.613+0000] {standard_task_runner.py:72} INFO - Started process 2548 to run task
[2024-12-19T08:51:32.626+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'second_task', 'scheduled__2021-09-30T00:00:00+00:00', '--job-id', '486', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpt0zkqur6']
[2024-12-19T08:51:32.641+0000] {standard_task_runner.py:105} INFO - Job 486: Subtask second_task
[2024-12-19T08:51:32.780+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v2.second_task scheduled__2021-09-30T00:00:00+00:00 [running]> on host 8d142e9c83a7
[2024-12-19T08:51:32.988+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2021-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-09-30T00:00:00+00:00'
[2024-12-19T08:51:32.992+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T08:51:33.028+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T08:51:33.047+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am the second task and i will me executed after first task']
[2024-12-19T08:51:33.072+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T08:51:33.088+0000] {subprocess.py:106} INFO - I am the second task and i will me executed after first task
[2024-12-19T08:51:33.091+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-19T08:51:33.131+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T08:51:33.133+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=second_task, run_id=scheduled__2021-09-30T00:00:00+00:00, execution_date=20210930T000000, start_date=20241219T085132, end_date=20241219T085133
[2024-12-19T08:51:33.201+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-19T08:51:33.222+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
