[2024-12-19T08:51:17.381+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T08:51:17.419+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.first_task scheduled__2021-08-29T00:00:00+00:00 [queued]>
[2024-12-19T08:51:17.436+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.first_task scheduled__2021-08-29T00:00:00+00:00 [queued]>
[2024-12-19T08:51:17.437+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-19T08:51:17.512+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): first_task> on 2021-08-29 00:00:00+00:00
[2024-12-19T08:51:17.534+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'first_task', 'scheduled__2021-08-29T00:00:00+00:00', '--job-id', '413', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpx5jttox1']
[2024-12-19T08:51:17.537+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2233) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-19T08:51:17.544+0000] {standard_task_runner.py:105} INFO - Job 413: Subtask first_task
[2024-12-19T08:51:17.545+0000] {standard_task_runner.py:72} INFO - Started process 2246 to run task
[2024-12-19T08:51:17.670+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v2.first_task scheduled__2021-08-29T00:00:00+00:00 [running]> on host 8d142e9c83a7
[2024-12-19T08:51:17.849+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2021-08-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-08-29T00:00:00+00:00'
[2024-12-19T08:51:17.852+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T08:51:17.908+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T08:51:17.910+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is the first task']
[2024-12-19T08:51:17.931+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T08:51:17.934+0000] {subprocess.py:106} INFO - hello world, this is the first task
[2024-12-19T08:51:17.935+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-19T08:51:17.980+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T08:51:17.981+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=first_task, run_id=scheduled__2021-08-29T00:00:00+00:00, execution_date=20210829T000000, start_date=20241219T085117, end_date=20241219T085117
[2024-12-19T08:51:18.058+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-19T08:51:18.096+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-19T08:51:18.101+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
