[2024-12-19T09:01:10.753+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T09:01:10.779+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.third_task scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-12-19T09:01:10.793+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.third_task scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-12-19T09:01:10.794+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-19T09:01:10.810+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): third_task> on 2024-10-09 00:00:00+00:00
[2024-12-19T09:01:10.822+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=13484) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-19T09:01:10.829+0000] {standard_task_runner.py:72} INFO - Started process 13492 to run task
[2024-12-19T09:01:10.827+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'third_task', 'scheduled__2024-10-09T00:00:00+00:00', '--job-id', '3168', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp_3u9s0t5']
[2024-12-19T09:01:10.834+0000] {standard_task_runner.py:105} INFO - Job 3168: Subtask third_task
[2024-12-19T09:01:10.906+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v2.third_task scheduled__2024-10-09T00:00:00+00:00 [running]> on host 8d142e9c83a7
[2024-12-19T09:01:11.009+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-09T00:00:00+00:00'
[2024-12-19T09:01:11.012+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T09:01:11.033+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T09:01:11.035+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am the third task and I will be executed at the same time as the second task.']
[2024-12-19T09:01:11.053+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T09:01:11.057+0000] {subprocess.py:106} INFO - I am the third task and I will be executed at the same time as the second task.
[2024-12-19T09:01:11.058+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-19T09:01:11.094+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T09:01:11.095+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=third_task, run_id=scheduled__2024-10-09T00:00:00+00:00, execution_date=20241009T000000, start_date=20241219T090110, end_date=20241219T090111
[2024-12-19T09:01:11.128+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-19T09:01:11.162+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-19T09:01:11.184+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
