[2024-12-19T08:57:58.247+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T08:57:58.278+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.third_task scheduled__2023-10-20T00:00:00+00:00 [queued]>
[2024-12-19T08:57:58.299+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.third_task scheduled__2023-10-20T00:00:00+00:00 [queued]>
[2024-12-19T08:57:58.300+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-19T08:57:58.389+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): third_task> on 2023-10-20 00:00:00+00:00
[2024-12-19T08:57:58.404+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=9166) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-19T08:57:58.413+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'third_task', 'scheduled__2023-10-20T00:00:00+00:00', '--job-id', '2107', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmprzutkuzl']
[2024-12-19T08:57:58.425+0000] {standard_task_runner.py:72} INFO - Started process 9179 to run task
[2024-12-19T08:57:58.430+0000] {standard_task_runner.py:105} INFO - Job 2107: Subtask third_task
[2024-12-19T08:57:58.551+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v2.third_task scheduled__2023-10-20T00:00:00+00:00 [running]> on host 8d142e9c83a7
[2024-12-19T08:57:58.813+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-20T00:00:00+00:00'
[2024-12-19T08:57:58.823+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T08:57:58.928+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T08:57:58.930+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am the third task and I will be executed at the same time as the second task.']
[2024-12-19T08:57:58.963+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T08:57:58.975+0000] {subprocess.py:106} INFO - I am the third task and I will be executed at the same time as the second task.
[2024-12-19T08:57:58.976+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-19T08:57:59.024+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T08:57:59.026+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=third_task, run_id=scheduled__2023-10-20T00:00:00+00:00, execution_date=20231020T000000, start_date=20241219T085758, end_date=20241219T085759
[2024-12-19T08:57:59.172+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-19T08:57:59.203+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-19T08:57:59.206+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
