[2024-12-19T09:00:42.246+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T09:00:42.292+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.third_task scheduled__2024-08-21T00:00:00+00:00 [queued]>
[2024-12-19T09:00:42.319+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.third_task scheduled__2024-08-21T00:00:00+00:00 [queued]>
[2024-12-19T09:00:42.321+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-19T09:00:42.388+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): third_task> on 2024-08-21 00:00:00+00:00
[2024-12-19T09:00:42.424+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=12865) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-19T09:00:42.441+0000] {standard_task_runner.py:72} INFO - Started process 12890 to run task
[2024-12-19T09:00:42.438+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'third_task', 'scheduled__2024-08-21T00:00:00+00:00', '--job-id', '3021', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpujf3r4xq']
[2024-12-19T09:00:42.473+0000] {standard_task_runner.py:105} INFO - Job 3021: Subtask third_task
[2024-12-19T09:00:42.607+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v2.third_task scheduled__2024-08-21T00:00:00+00:00 [running]> on host 8d142e9c83a7
[2024-12-19T09:00:42.739+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-21T00:00:00+00:00'
[2024-12-19T09:00:42.741+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T09:00:42.765+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T09:00:42.766+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am the third task and I will be executed at the same time as the second task.']
[2024-12-19T09:00:42.784+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T09:00:42.786+0000] {subprocess.py:106} INFO - I am the third task and I will be executed at the same time as the second task.
[2024-12-19T09:00:42.788+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-19T09:00:42.817+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T09:00:42.818+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=third_task, run_id=scheduled__2024-08-21T00:00:00+00:00, execution_date=20240821T000000, start_date=20241219T090042, end_date=20241219T090042
[2024-12-19T09:00:42.870+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-19T09:00:42.881+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
