[2024-12-19T08:55:38.120+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T08:55:38.159+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.second_task scheduled__2023-03-28T00:00:00+00:00 [queued]>
[2024-12-19T08:55:38.187+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.second_task scheduled__2023-03-28T00:00:00+00:00 [queued]>
[2024-12-19T08:55:38.190+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-19T08:55:38.241+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): second_task> on 2023-03-28 00:00:00+00:00
[2024-12-19T08:55:38.257+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'second_task', 'scheduled__2023-03-28T00:00:00+00:00', '--job-id', '1575', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp8holzqtb']
[2024-12-19T08:55:38.262+0000] {standard_task_runner.py:105} INFO - Job 1575: Subtask second_task
[2024-12-19T08:55:38.262+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6987) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-19T08:55:38.264+0000] {standard_task_runner.py:72} INFO - Started process 6999 to run task
[2024-12-19T08:55:38.331+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v2.second_task scheduled__2023-03-28T00:00:00+00:00 [running]> on host 8d142e9c83a7
[2024-12-19T08:55:38.493+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2023-03-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-28T00:00:00+00:00'
[2024-12-19T08:55:38.495+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T08:55:38.515+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T08:55:38.517+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am the second task and i will me executed after first task']
[2024-12-19T08:55:38.532+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T08:55:38.534+0000] {subprocess.py:106} INFO - I am the second task and i will me executed after first task
[2024-12-19T08:55:38.535+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-19T08:55:38.558+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T08:55:38.559+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=second_task, run_id=scheduled__2023-03-28T00:00:00+00:00, execution_date=20230328T000000, start_date=20241219T085538, end_date=20241219T085538
[2024-12-19T08:55:38.606+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-19T08:55:38.622+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-19T08:55:38.624+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
